import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { ACADEMIC_PORTION_MOCK_TEST_1 } from '../src/data/academicPortionMockTest1.js';
import { ACADEMIC_PORTION_MOCK_TEST_2 } from '../src/data/academicPortionMockTest2.js';
import { PMA_LONG_COURSE_159_MOCK_TEST_2 } from '../src/data/pmaLongCourse159MockTest2.js';
import { PMA_LONG_COURSE_159_MOST_REPEATED_QUESTIONS_BANK } from '../src/data/pmaLongCourse159MostRepeatedQuestionsBank.js';
import { PMA_LONG_COURSE_159_MUST_COME_QUESTIONS_BANK } from '../src/data/pmaLongCourse159MustComeQuestionsBank.js';

const migration = readFileSync(fileURLToPath(new URL('../supabase/migrations/025_mock_test_purchases.sql', import.meta.url)), 'utf8');
const perUserAccessMigration = readFileSync(fileURLToPath(new URL('../supabase/migrations/027_enforce_per_user_paid_mock_test_access.sql', import.meta.url)), 'utf8');
const bankMigration = readFileSync(fileURLToPath(new URL('../supabase/migrations/026_seed_paid_mock_test_question_banks.sql', import.meta.url)), 'utf8');
const mostRepeatedBankMigration = readFileSync(fileURLToPath(new URL('../supabase/migrations/028_refresh_most_repeated_mock_test_question_bank.sql', import.meta.url)), 'utf8');
const mostRepeatedPurchaseMigration = readFileSync(fileURLToPath(new URL('../supabase/migrations/029_allow_most_repeated_mock_test_purchase.sql', import.meta.url)), 'utf8');
const legacyPurchaseConstraintMigration = readFileSync(fileURLToPath(new URL('../supabase/migrations/030_fix_mock_test_purchase_product_constraints.sql', import.meta.url)), 'utf8');
const paymentAccessRepairMigration = readFileSync(fileURLToPath(new URL('../supabase/migrations/031_repair_mock_test_payment_and_access.sql', import.meta.url)), 'utf8');
const mustComePurchaseMigration = readFileSync(fileURLToPath(new URL('../supabase/migrations/032_add_must_come_mock_test_purchase.sql', import.meta.url)), 'utf8');
const mustComeBankMigration = readFileSync(fileURLToPath(new URL('../supabase/migrations/033_seed_must_come_mock_test_question_bank.sql', import.meta.url)), 'utf8');
const paidAcademicTestMigration = readFileSync(fileURLToPath(new URL('../supabase/migrations/036_add_paid_academic_portion_mock_test_1.sql', import.meta.url)), 'utf8');
const academicTestOneModule = readFileSync(fileURLToPath(new URL('../src/data/academicPortionMockTest1.js', import.meta.url)), 'utf8');
const academicModule = readFileSync(fileURLToPath(new URL('../src/data/academicPortionMockTest2.js', import.meta.url)), 'utf8');
const pmaModule = readFileSync(fileURLToPath(new URL('../src/data/pmaLongCourse159MockTest2.js', import.meta.url)), 'utf8');
const mostRepeatedQuestions = JSON.parse(readFileSync(fileURLToPath(new URL('../src/data/pmaLongCourse159MostRepeatedQuestionsBank.json', import.meta.url)), 'utf8'));
const mustComeQuestions = JSON.parse(readFileSync(fileURLToPath(new URL('../src/data/pmaLongCourse159MustComeQuestionsBank.json', import.meta.url)), 'utf8'));
const academicTestOneQuestions = JSON.parse(readFileSync(fileURLToPath(new URL('../src/data/academicPortionMockTest1.json', import.meta.url)), 'utf8'));
const appSource = readFileSync(fileURLToPath(new URL('../src/App.jsx', import.meta.url)), 'utf8');

const getSeededBank = (migrationSource, slug) => {
  const prefix = `('${slug}', convert_from(decode('`;
  const start = migrationSource.indexOf(prefix);
  assert.notEqual(start, -1, `Missing seeded question bank ${slug}`);
  const jsonStart = start + prefix.length;
  const end = migrationSource.indexOf("', 'base64'), 'UTF8')::jsonb)", jsonStart);
  assert.notEqual(end, -1, `Missing JSON terminator for ${slug}`);
  return JSON.parse(Buffer.from(migrationSource.slice(jsonStart, end), 'base64').toString('utf8'));
};

test('mock-test payments use fixed product prices and pending approval', () => {
  assert.equal(ACADEMIC_PORTION_MOCK_TEST_1.title, 'Academic Portion Mock Test 1');
  assert.equal(ACADEMIC_PORTION_MOCK_TEST_1.questionsCount, 100);
  assert.equal(ACADEMIC_PORTION_MOCK_TEST_1.pricePkr, 30);
  assert.doesNotMatch(academicTestOneModule, /academicPortionMockTest1\.json/);
  assert.match(paidAcademicTestMigration, /academic-portion-mock-test-1' and amount_pkr = 30/);
  assert.match(paidAcademicTestMigration, /academic-portion-mock-test-1' then 30/);
  assert.match(paidAcademicTestMigration, /academic-portion-mock-test-1' then 'Academic Portion Mock Test 1'/);
  assert.equal(PMA_LONG_COURSE_159_MOCK_TEST_2.title, 'PMA Long Course 159 Mock Test 2');
  assert.equal(PMA_LONG_COURSE_159_MOCK_TEST_2.pricePkr, 49);
  assert.equal(PMA_LONG_COURSE_159_MOST_REPEATED_QUESTIONS_BANK.title, 'PMA Long Course 159 Most Repeated Questions Bank');
  assert.equal(PMA_LONG_COURSE_159_MOST_REPEATED_QUESTIONS_BANK.pricePkr, 79);
  assert.equal(PMA_LONG_COURSE_159_MOST_REPEATED_QUESTIONS_BANK.duration, '150 mins');
  assert.equal(PMA_LONG_COURSE_159_MUST_COME_QUESTIONS_BANK.title, 'PMA Long Course 159 Must Come Questions Bank');
  assert.equal(PMA_LONG_COURSE_159_MUST_COME_QUESTIONS_BANK.pricePkr, 99);
  assert.equal(PMA_LONG_COURSE_159_MUST_COME_QUESTIONS_BANK.duration, '120 mins');
  assert.equal(ACADEMIC_PORTION_MOCK_TEST_2.title, 'Academic Portion Mock Test 2');
  assert.equal(ACADEMIC_PORTION_MOCK_TEST_2.pricePkr, 20);
  assert.match(migration, /pma-long-course-159-mock-test-2' then 49/);
  assert.match(migration, /pma-long-course-159-most-repeated-questions-bank' then 79/);
  assert.match(migration, /academic-portion-mock-test-2' then 20/);
  assert.match(migration, /'PENDING'/);
  assert.match(migration, /payment_screenshot_url text not null/);
  assert.match(mostRepeatedPurchaseMigration, /drop constraint if exists paid_mock_test_question_banks_test_slug_check/i);
  assert.match(mostRepeatedPurchaseMigration, /add constraint paid_mock_test_question_banks_test_slug_check\s+check \(test_slug in \([\s\S]*?'pma-long-course-159-most-repeated-questions-bank'/i);
  assert.match(mostRepeatedPurchaseMigration, /add constraint mock_test_purchase_requests_amount_pkr_check\s+check \([\s\S]*?'pma-long-course-159-most-repeated-questions-bank' and amount_pkr = 79/i);
  assert.ok(mostRepeatedBankMigration.indexOf('add constraint paid_mock_test_question_banks_test_slug_check') < mostRepeatedBankMigration.indexOf('insert into public.paid_mock_test_question_banks'));
  assert.match(legacyPurchaseConstraintMigration, /drop constraint if exists mock_test_purchase_requests_check/i);
  assert.match(legacyPurchaseConstraintMigration, /add constraint mock_test_purchase_requests_test_slug_check[\s\S]*?'pma-long-course-159-most-repeated-questions-bank'/i);
  assert.match(legacyPurchaseConstraintMigration, /add constraint mock_test_purchase_requests_amount_pkr_check[\s\S]*?'pma-long-course-159-most-repeated-questions-bank' and amount_pkr = 79/i);
  assert.match(paymentAccessRepairMigration, /drop constraint if exists mock_test_purchase_requests_check/i);
  assert.match(paymentAccessRepairMigration, /payment_method[\s\S]*?NAYAPAY_MANUAL/);
  assert.match(paymentAccessRepairMigration, /'pma-long-course-159-most-repeated-questions-bank' then 79/);
  assert.match(paymentAccessRepairMigration, /select 1 from public\.mock_test_purchase_requests[\s\S]*?where user_id = v_user_id[\s\S]*?test_slug = p_test_slug[\s\S]*?status = 'PENDING'/);
  assert.match(paymentAccessRepairMigration, /insert into public\.mock_test_purchase_requests \([\s\S]*?user_id, test_slug, amount_pkr/);
  assert.match(paymentAccessRepairMigration, /v_user_id, p_test_slug, v_amount_pkr, 'NAYAPAY_MANUAL'/);
  assert.match(paymentAccessRepairMigration, /'PENDING'[\s\S]*?Access will be enabled after admin approval/);
  assert.match(paymentAccessRepairMigration, /drop constraint if exists paid_mock_test_question_banks_test_slug_check/i);
  assert.match(paymentAccessRepairMigration, /purchase\.user_id = v_user_id[\s\S]*?purchase\.test_slug = p_test_slug[\s\S]*?purchase\.status = 'APPROVED'/);
  assert.doesNotMatch(paymentAccessRepairMigration.slice(paymentAccessRepairMigration.indexOf('create or replace function public.get_paid_mock_test_questions')), /status = 'PENDING'|is_editor_or_admin|from public\.subscriptions/i);
  assert.match(paymentAccessRepairMigration, /revoke all on table public\.paid_mock_test_question_banks from public, anon, authenticated/i);
  assert.match(paymentAccessRepairMigration, /revoke all on function public\.get_paid_mock_test_questions\(text\) from public, anon/i);
  assert.match(paymentAccessRepairMigration, /grant execute on function public\.get_paid_mock_test_questions\(text\) to authenticated/i);
  assert.match(mustComePurchaseMigration, /'pma-long-course-159-must-come-questions-bank' and amount_pkr = 99/);
  assert.match(mustComePurchaseMigration, /'pma-long-course-159-must-come-questions-bank' then 99/);
  assert.match(mustComePurchaseMigration, /purchase\.user_id = v_user_id[\s\S]*?purchase\.test_slug = p_test_slug[\s\S]*?purchase\.status = 'APPROVED'/);
});

test('approved mock-test purchases grant permanent access without plan upgrades', () => {
  const accessFunction = migration.slice(migration.indexOf('create or replace function public.get_paid_mock_test_questions'));
  assert.match(accessFunction, /purchase\.user_id = v_user_id/);
  assert.match(accessFunction, /purchase\.test_slug = p_test_slug/);
  assert.match(accessFunction, /purchase\.status = 'APPROVED'/);
  assert.doesNotMatch(accessFunction, /is_editor_or_admin|from public\.subscriptions/i);
  assert.match(perUserAccessMigration, /purchase\.user_id = v_user_id/);
  assert.match(perUserAccessMigration, /purchase\.status = 'APPROVED'/);
  assert.doesNotMatch(perUserAccessMigration, /is_editor_or_admin|from public\.subscriptions/i);
  assert.match(migration, /function public\.admin_approve_mock_test_purchase/);
  assert.doesNotMatch(migration.slice(migration.indexOf('function public.admin_approve_mock_test_purchase'), migration.indexOf('function public.admin_reject_mock_test_purchase')), /insert into public\.subscriptions/i);
  assert.match(migration, /on public\.mock_test_purchase_requests \(user_id, test_slug\)\s+where status in \('PENDING', 'APPROVED'\)/);
  assert.doesNotMatch(migration, /mock_test_global_access|global_unlocked/i);
  assert.doesNotMatch(perUserAccessMigration, /mock_test_global_access|global_unlocked/i);
  assert.match(migration, /alter table public\.paid_mock_test_question_banks enable row level security/i);
  assert.match(migration, /revoke all on table public\.paid_mock_test_question_banks from anon, authenticated/i);
  assert.doesNotMatch(academicModule, /academicPortionMockTest2\.json/);
  assert.doesNotMatch(pmaModule, /pmaLongCourse159MockTest2\.json/);
});

test('paid test UI refreshes anonymous ownership and never bypasses approval', () => {
  const cardAction = appSource.slice(appSource.indexOf('const renderPaidTestAction'), appSource.indexOf('\n\n    return (', appSource.indexOf('const renderPaidTestAction')));
  const paidProducts = appSource.slice(appSource.indexOf('const PAID_MOCK_TEST_PRODUCTS'), appSource.indexOf('];', appSource.indexOf('const PAID_MOCK_TEST_PRODUCTS')));
  const startHandler = appSource.slice(appSource.indexOf('const startPaidMockTest'), appSource.indexOf('const handleAdminPaymentAction', appSource.indexOf('const startPaidMockTest')));
  const paymentPage = appSource.slice(appSource.indexOf('const renderMockTestPaymentPage'), appSource.indexOf('const renderMockTestsPage', appSource.indexOf('const renderMockTestPaymentPage')));

  assert.match(paidProducts, /PMA_LONG_COURSE_159_MOST_REPEATED_QUESTIONS_BANK/);
  assert.match(paidProducts, /PMA_LONG_COURSE_159_MUST_COME_QUESTIONS_BANK/);
  assert.match(paidProducts, /ACADEMIC_PORTION_MOCK_TEST_1/);
  assert.match(appSource, /renderPaidTestAction\(localMockTest\)/);
  assert.match(cardAction, /request\?\.status === 'APPROVED'/);
  assert.doesNotMatch(cardAction, /canAccessPremiumResources/);
  assert.match(startHandler, /await ensureAnonymousSession\(\)/);
  assert.ok(startHandler.indexOf('await getMyMockTestPurchases()') < startHandler.indexOf('await getPaidMockTestQuestions'));
  assert.match(startHandler, /navigateTo\('mock-payment', product\.id\)/);
  assert.match(paymentPage, /const hasAccess = latestRequest\?\.status === 'APPROVED'/);
});

test('protected database seed contains the complete paid question banks', () => {
  const academicTestOneSeed = getSeededBank(paidAcademicTestMigration, 'academic-portion-mock-test-1');
  const pmaQuestions = getSeededBank(bankMigration, 'pma-long-course-159-mock-test-2');
  const seededMostRepeatedQuestions = getSeededBank(bankMigration, 'pma-long-course-159-most-repeated-questions-bank');
  const updatedMostRepeatedQuestions = getSeededBank(mostRepeatedBankMigration, 'pma-long-course-159-most-repeated-questions-bank');
  const academicQuestions = getSeededBank(bankMigration, 'academic-portion-mock-test-2');
  const seededMustComeQuestions = getSeededBank(bankMigration, 'pma-long-course-159-must-come-questions-bank');
  assert.equal(mustComeQuestions.length, 220);
  assert.deepEqual(seededMustComeQuestions, mustComeQuestions);
  assert.equal(seededMustComeQuestions[0].question_text, 'Synonym of ABUNDANT:');
  assert.equal(seededMustComeQuestions[0].option_b, 'Plentiful');
  assert.ok(seededMustComeQuestions.slice(60, 120).every((question) => question.image_url));
  assert.ok(seededMustComeQuestions.every((question) => question.correct_option && question.explanation));
  assert.match(mustComeBankMigration, /pma-long-course-159-must-come-questions-bank/);
  assert.equal(pmaQuestions.length, 220);
  assert.equal(seededMostRepeatedQuestions.length, 220);
  assert.deepEqual(seededMostRepeatedQuestions, mostRepeatedQuestions);
  assert.deepEqual(updatedMostRepeatedQuestions, mostRepeatedQuestions);
  const updatedBankInsert = mostRepeatedBankMigration.slice(mostRepeatedBankMigration.indexOf('insert into public.paid_mock_test_question_banks'), mostRepeatedBankMigration.indexOf('on conflict'));
  assert.match(updatedBankInsert, /^\s*insert into public\.paid_mock_test_question_banks \(test_slug, questions\) values\s+\('pma-long-course-159-most-repeated-questions-bank'/);
  assert.equal((updatedBankInsert.match(/\('pma-long-course-/g) || []).length, 1);
  assert.equal(seededMostRepeatedQuestions[0].question_text, 'Synonym of ZENITH:');
  assert.equal(seededMostRepeatedQuestions[0].option_c, 'Peak');
  assert.notEqual(seededMostRepeatedQuestions[0].question_text, pmaQuestions[0].question_text);
  assert.ok(seededMostRepeatedQuestions.slice(60, 120).every((question) => question.image_url));
  assert.equal(academicQuestions.length, 100);
  assert.deepEqual(academicTestOneSeed, academicTestOneQuestions);
  assert.match(paidAcademicTestMigration, /purchase\.user_id = v_user_id[\s\S]*?purchase\.test_slug = p_test_slug[\s\S]*?purchase\.status = 'APPROVED'/);
  assert.equal(pmaQuestions[60].image_url, '/images/mock-tests/pma-lc159-mock-test-2/q061.png');
  assert.ok(pmaQuestions.every((question) => question.correct_option && question.explanation));
  assert.ok(seededMostRepeatedQuestions.every((question) => question.correct_option && question.explanation));
  assert.ok(academicQuestions.every((question) => question.correct_option && question.explanation));
});