begin;

drop index if exists public.questions_question_text_unique_idx;
create unique index if not exists questions_question_text_unkeyed_unique_idx
  on public.questions (question_text) where content_key is null;

insert into public.subjects (name, slug, description, display_order) values
  ('Physics', 'physics', 'Physics questions from the first full PMA mock test.', 16)
on conflict (slug) do nothing;

insert into public.mock_tests (title, slug, description, branch_id, exam_id, duration_minutes, total_questions, difficulty, is_premium, is_active, category)
select '1st Full Mock Test', 'first-full-mock-test',
       'PMA Long Course 159 full-length paper: 200 questions across verbal and non-verbal intelligence, physics, English, and general knowledge.',
       branch.id, exam.id, 105, 200, 'MEDIUM', false, true, 'Full Mock Test'
from public.military_branches branch
join public.exams exam on exam.slug = 'pma-long-course-initial-test'
where branch.slug = 'pak-army'
on conflict (slug) do update set
  title = excluded.title, description = excluded.description, branch_id = excluded.branch_id,
  exam_id = excluded.exam_id, duration_minutes = excluded.duration_minutes, total_questions = excluded.total_questions,
  difficulty = excluded.difficulty, is_premium = excluded.is_premium, is_active = true, category = excluded.category, updated_at = now();

with first_full_mock_seed (question_number, subject_slug, category, question_text, question_type, difficulty, option_a, option_b, option_c, option_d, correct_option, explanation, image_url) as (
values
(1, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 3, 6, 12, 24, ?', 'MCQ', 'EASY', '36', '42', '48', '52', 'C', 'Each term is doubled (×2): 24 × 2 = 48.', null),
(2, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 100, 91, 82, 73, ?', 'MCQ', 'EASY', '65', '62', '66', '64', 'D', 'Each term decreases by 9: 73 − 9 = 64.', null),
(3, 'verbal-intelligence', 'Verbal Intelligence', 'Pen : Write :: Knife : ?', 'MCQ', 'EASY', 'Sharp', 'Steel', 'Kitchen', 'Cut', 'D', 'A pen is used to write; a knife is used to cut (function relationship).', null),
(4, 'verbal-intelligence', 'Verbal Intelligence', 'Doctor : Hospital :: Teacher : ?', 'MCQ', 'EASY', 'Student', 'School', 'Book', 'Chalk', 'B', 'A doctor works in a hospital; a teacher works in a school (worker : workplace).', null),
(5, 'verbal-intelligence', 'Verbal Intelligence', 'Which one is different from the rest? Apple, Mango, Banana, Potato', 'MCQ', 'EASY', 'Apple', 'Mango', 'Potato', 'Banana', 'C', 'Apple, mango and banana are fruits; potato is a vegetable.', null),
(6, 'verbal-intelligence', 'Verbal Intelligence', 'Which one is different from the rest? Karachi, Lahore, Quetta, Indus', 'MCQ', 'EASY', 'Lahore', 'Indus', 'Karachi', 'Quetta', 'B', 'Karachi, Lahore and Quetta are cities; the Indus is a river.', null),
(7, 'verbal-intelligence', 'Verbal Intelligence', 'Find the next letter: A, C, E, G, ?', 'MCQ', 'EASY', 'K', 'H', 'I', 'J', 'C', 'Alternate letters are skipped (+2 positions): G (7) → I (9).', null),
(8, 'verbal-intelligence', 'Verbal Intelligence', 'If CAT is written as DBU, how will DOG be written in the same code?', 'MCQ', 'EASY', 'EOH', 'DPH', 'CNF', 'EPH', 'D', 'Every letter is moved one step forward: D→E, O→P, G→H, so DOG = EPH.', null),
(9, 'verbal-intelligence', 'Verbal Intelligence', 'Pointing to a man, Ali said, "He is the son of my father''s only son." How is the man related to Ali?', 'MCQ', 'EASY', 'Father', 'Brother', 'Nephew', 'Son', 'D', 'Ali''s father''s only son is Ali himself. So the man is Ali''s son.', null),
(10, 'verbal-intelligence', 'Verbal Intelligence', 'Ahmed walks 5 km towards the north, then turns right and walks 5 km. In which direction is he now from his starting point?', 'MCQ', 'EASY', 'North-West', 'East', 'North-East', 'South-East', 'C', 'North 5 km and then East 5 km (right turn) puts him exactly north-east of the start.', null),
(11, 'verbal-intelligence', 'Verbal Intelligence', 'In a row of 20 students, Ali is 8th from the left. What is his position from the right end?', 'MCQ', 'EASY', '11', '13', '14', '12', 'B', 'Position from right = 20 − 8 + 1 = 13.', null),
(12, 'verbal-intelligence', 'Verbal Intelligence', 'What is 15% of 200?', 'MCQ', 'EASY', '25', '30', '20', '35', 'B', '15/100 × 200 = 30.', null),
(13, 'verbal-intelligence', 'Verbal Intelligence', 'If today is Monday, what day of the week will it be after 10 days?', 'MCQ', 'EASY', 'Tuesday', 'Friday', 'Wednesday', 'Thursday', 'D', '10 = 7 + 3, so count 3 days ahead of Monday: Thursday.', null),
(14, 'verbal-intelligence', 'Verbal Intelligence', 'Select the word opposite in meaning to ANCIENT.', 'MCQ', 'EASY', 'Old', 'Historic', 'Modern', 'Antique', 'C', 'Ancient means very old; its opposite is modern.', null),
(15, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 1, 4, 9, 16, 25, ?', 'MCQ', 'EASY', '35', '30', '49', '36', 'D', 'These are perfect squares: 1², 2², 3², 4², 5², 6² = 36.', null),
(16, 'verbal-intelligence', 'Verbal Intelligence', 'What time will it be 3 hours 45 minutes after 8:30 a.m.?', 'MCQ', 'EASY', '12:05 p.m.', '12:45 p.m.', '11:15 a.m.', '12:15 p.m.', 'D', '8:30 + 3:45 = 12:15.', null),
(17, 'verbal-intelligence', 'Verbal Intelligence', 'What is the average of 10, 20, 30 and 40?', 'MCQ', 'EASY', '20', '25', '100', '30', 'B', 'Sum = 100; 100 ÷ 4 = 25.', null),
(18, 'verbal-intelligence', 'Verbal Intelligence', 'Ahmed is taller than Bilal, and Bilal is taller than Kamran. Who is the shortest of the three?', 'MCQ', 'EASY', 'Ahmed', 'Kamran', 'Bilal', 'Cannot be determined', 'B', 'Ahmed > Bilal > Kamran, so Kamran is the shortest.', null),
(19, 'verbal-intelligence', 'Verbal Intelligence', 'Which number is different from the rest? 2, 3, 5, 9, 11', 'MCQ', 'EASY', '5', '11', '2', '9', 'D', '2, 3, 5 and 11 are prime numbers; 9 = 3 × 3 is not.', null),
(20, 'verbal-intelligence', 'Verbal Intelligence', 'Find the next pair: AB, CD, EF, GH, ?', 'MCQ', 'EASY', 'JK', 'IK', 'HI', 'IJ', 'D', 'Consecutive letters in pairs: after GH comes IJ.', null),
(21, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 2, 6, 12, 20, 30, ?', 'MCQ', 'MEDIUM', '42', '44', '40', '36', 'A', 'Differences are 4, 6, 8, 10, so the next difference is 12: 30 + 12 = 42 (terms are n × (n+1)).', null),
(22, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 1, 2, 6, 24, 120, ?', 'MCQ', 'MEDIUM', '240', '720', '840', '600', 'B', 'Multiply by 2, 3, 4, 5, then 6: 120 × 6 = 720 (factorials).', null),
(23, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 2, 3, 5, 7, 11, 13, ?', 'MCQ', 'MEDIUM', '17', '15', '19', '21', 'A', 'The series is of prime numbers; the next prime after 13 is 17.', null),
(24, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 5, 11, 23, 47, ?', 'MCQ', 'MEDIUM', '91', '95', '96', '94', 'B', 'Each term = previous × 2 + 1: 47 × 2 + 1 = 95.', null),
(25, 'verbal-intelligence', 'Verbal Intelligence', 'Find the next letter: B, E, H, K, N, ?', 'MCQ', 'MEDIUM', 'R', 'P', 'Q', 'S', 'C', 'Each letter moves 3 steps forward: N (14) + 3 = 17 = Q.', null),
(26, 'verbal-intelligence', 'Verbal Intelligence', 'Find the next pair: AZ, BY, CX, DW, ?', 'MCQ', 'MEDIUM', 'DV', 'EV', 'EU', 'FV', 'B', 'The first letter moves forward (A, B, C, D, E) and the second moves backward (Z, Y, X, W, V).', null),
(27, 'verbal-intelligence', 'Verbal Intelligence', '5 : 125 :: 6 : ?', 'MCQ', 'MEDIUM', '216', '186', '36', '196', 'A', '5³ = 125, so 6³ = 216 (number : its cube).', null),
(28, 'verbal-intelligence', 'Verbal Intelligence', 'Bird : Nest :: Bee : ?', 'MCQ', 'MEDIUM', 'Wing', 'Honey', 'Hive', 'Flower', 'C', 'A nest is the home of a bird; a hive is the home of a bee.', null),
(29, 'verbal-intelligence', 'Verbal Intelligence', 'In a certain code, TABLE is written as UBCMF. How will CHAIR be written in that code?', 'MCQ', 'MEDIUM', 'DIBJQ', 'DJCKT', 'DIBJS', 'BGZHQ', 'C', 'Every letter is moved one step forward: C→D, H→I, A→B, I→J, R→S.', null),
(30, 'verbal-intelligence', 'Verbal Intelligence', 'If A = 1, B = 2, C = 3 … Z = 26, what is the sum of the letter values of the word ARMY?', 'MCQ', 'MEDIUM', '56', '57', '55', '59', 'B', 'A(1) + R(18) + M(13) + Y(25) = 57.', null),
(31, 'verbal-intelligence', 'Verbal Intelligence', 'A is the sister of B. C is the mother of B. D is the father of C. How is A related to D?', 'MCQ', 'MEDIUM', 'Daughter', 'Niece', 'Sister', 'Granddaughter', 'D', 'A and B are children of C. D is C''s father, so D is A''s grandfather and A is his granddaughter.', null),
(32, 'verbal-intelligence', 'Verbal Intelligence', 'Pointing to a lady, Sara said, "She is the daughter of my father''s only brother." How is the lady related to Sara?', 'MCQ', 'MEDIUM', 'Cousin', 'Sister', 'Aunt', 'Niece', 'A', 'Father''s brother''s daughter is a cousin.', null),
(33, 'verbal-intelligence', 'Verbal Intelligence', 'Rashid is facing North. He turns 135° clockwise and then 90° anticlockwise. Which direction is he facing now?', 'MCQ', 'MEDIUM', 'East', 'North-West', 'North-East', 'South-East', 'C', 'Facing north (0°): +135° → 135°; −90° → 45°, which is North-East.', null),
(34, 'verbal-intelligence', 'Verbal Intelligence', 'A man walks 8 m towards the west and then 6 m towards the north. How far is he from his starting point?', 'MCQ', 'MEDIUM', '10 m', '8 m', '12 m', '14 m', 'A', 'Straight-line distance = √(8² + 6²) = √100 = 10 m.', null),
(35, 'verbal-intelligence', 'Verbal Intelligence', 'Hamza ranks 12th from the top and 25th from the bottom in a class. How many students are there in the class?', 'MCQ', 'MEDIUM', '36', '38', '37', '35', 'A', 'Total = 12 + 25 − 1 = 36.', null),
(36, 'verbal-intelligence', 'Verbal Intelligence', 'What is the angle between the hour hand and the minute hand of a clock at 3:30?', 'MCQ', 'MEDIUM', '60°', '105°', '75°', '90°', 'C', 'Hour hand at 3:30 = 105°; minute hand = 180°. Difference = 75°. (Formula: |30H − 5.5M| = |90 − 165| = 75°.)', null),
(37, 'verbal-intelligence', 'Verbal Intelligence', 'If 14 August 2026 is a Friday, what day of the week will 1 September 2026 be?', 'MCQ', 'MEDIUM', 'Wednesday', 'Tuesday', 'Monday', 'Thursday', 'B', 'From 14 Aug to 1 Sep is 18 days. 18 = 14 + 4, so 4 days after Friday is Tuesday.', null),
(38, 'verbal-intelligence', 'Verbal Intelligence', 'Statements: All soldiers are brave. Some brave persons are honest. Conclusions: I. Some soldiers are honest. II. All honest persons are soldiers.', 'MCQ', 'MEDIUM', 'Both I and II follow', 'Neither I nor II follows', 'Only II follows', 'Only I follows', 'B', 'The ''honest'' brave persons need not be soldiers, so I is not certain, and II is clearly not supported.', null),
(39, 'verbal-intelligence', 'Verbal Intelligence', 'Rs. 5,600 is divided between two persons in the ratio 3 : 4. What is the share of the person who gets the larger part?', 'MCQ', 'MEDIUM', 'Rs. 3,200', 'Rs. 2,800', 'Rs. 3,600', 'Rs. 2,400', 'A', 'Total parts = 7; one part = 5600 ÷ 7 = 800; larger share = 4 × 800 = 3,200.', null),
(40, 'verbal-intelligence', 'Verbal Intelligence', 'A car covers 180 km in 3 hours. At the same speed, how long will it take to cover 300 km?', 'MCQ', 'MEDIUM', '6 hours', '4.5 hours', '5 hours', '4 hours', 'C', 'Speed = 60 km/h; time = 300 ÷ 60 = 5 hours.', null),
(41, 'verbal-intelligence', 'Verbal Intelligence', 'A can finish a job in 12 days and B can finish it in 24 days. Working together, in how many days will they finish it?', 'MCQ', 'MEDIUM', '18 days', '6 days', '9 days', '8 days', 'D', 'Combined rate = 1/12 + 1/24 = 3/24 = 1/8 per day, so 8 days.', null),
(42, 'verbal-intelligence', 'Verbal Intelligence', 'A father is three times as old as his son. After 10 years he will be twice as old as his son. What is the present age of the son?', 'MCQ', 'MEDIUM', '8 years', '12 years', '10 years', '15 years', 'C', 'Let son = x. 3x + 10 = 2(x + 10) → x = 10.', null),
(43, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 3, 8, 15, 24, 35, ?', 'MCQ', 'HARD', '50', '48', '46', '49', 'B', 'Terms are n² − 1 for n = 2, 3, 4, 5, 6, so the next is 7² − 1 = 48.', null),
(44, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 2, 5, 10, 17, 26, ?', 'MCQ', 'HARD', '37', '38', '35', '39', 'A', 'Terms are n² + 1: 1²+1 = 2, 2²+1 = 5 … 6² + 1 = 37.', null),
(45, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 4, 6, 9, 13, 18, ?', 'MCQ', 'HARD', '22', '25', '24', '23', 'C', 'Differences are 2, 3, 4, 5, so the next difference is 6: 18 + 6 = 24.', null),
(46, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 6, 11, 21, 36, 56, ?', 'MCQ', 'HARD', '80', '81', '86', '76', 'B', 'Differences are 5, 10, 15, 20, so the next is 25: 56 + 25 = 81.', null),
(47, 'verbal-intelligence', 'Verbal Intelligence', 'Find the missing number: 2, 12, 36, 80, 150, ?', 'MCQ', 'HARD', '252', '262', '240', '210', 'A', 'Terms are n² × (n + 1): 1²×2, 2²×3, 3²×4, 4²×5, 5²×6, so the next is 6²×7 = 252.', null),
(48, 'verbal-intelligence', 'Verbal Intelligence', 'Find the next letter: Z, X, U, Q, L, ?', 'MCQ', 'HARD', 'E', 'F', 'G', 'H', 'B', 'Positions are 26, 24, 21, 17, 12 (differences −2, −3, −4, −5). Next difference −6: 12 − 6 = 6 = F.', null),
(49, 'verbal-intelligence', 'Verbal Intelligence', 'If the letters of the word MOUNTAIN are arranged in alphabetical order, which letter will be fourth from the left?', 'MCQ', 'HARD', 'M', 'O', 'N', 'T', 'C', 'A, I, M, N, N, O, T, U → the fourth letter is N.', null),
(50, 'verbal-intelligence', 'Verbal Intelligence', 'In a certain code, ARMY is written as ZINB. How will NAVY be written in that code?', 'MCQ', 'HARD', 'MZEB', 'MAEB', 'MZVB', 'OZEB', 'A', 'Each letter is replaced by its opposite letter (A↔Z, B↔Y … M↔N): N→M, A→Z, V→E, Y→B.', null),
(51, 'verbal-intelligence', 'Verbal Intelligence', 'If A + B means A is the mother of B, A − B means A is the brother of B, and A × B means A is the sister of B, which expression shows that P is the maternal uncle of Q?', 'MCQ', 'HARD', 'P + R − Q', 'P − R × Q', 'P × R + Q', 'P − R + Q', 'D', 'P − R: P is the brother of R. R + Q: R is the mother of Q. So P is Q''s mother''s brother, i.e. maternal uncle.', null),
(52, 'verbal-intelligence', 'Verbal Intelligence', 'Usman starts from point A, walks 10 m east, then 5 m south, then 6 m west and finally 5 m north. Where is he now with respect to A?', 'MCQ', 'HARD', '4 m west of A', 'At point A', '6 m east of A', '4 m east of A', 'D', 'Net east–west: 10 − 6 = 4 m east; net north–south: 5 S − 5 N = 0.', null),
(53, 'verbal-intelligence', 'Verbal Intelligence', 'Ali is 14th from the left end and Bilal is 9th from the right end of a row of boys. When they exchange places, Ali becomes 20th from the left. How many boys are in the row?', 'MCQ', 'HARD', '29', '30', '27', '28', 'D', 'Ali now stands where Bilal was: Bilal was 20th from left and 9th from right. Total = 20 + 9 − 1 = 28.', null),
(54, 'verbal-intelligence', 'Verbal Intelligence', 'At what time between 4 and 5 o''clock will the hands of a clock coincide?', 'MCQ', 'HARD', '4:21 9/11', '4:20', '4:24 6/11', '4:22 1/2', 'A', 'Minute hand gains 5.5° per minute; at 4:00 it is 120° behind. 120 ÷ 5.5 = 21 9/11 minutes after 4.', null),
(55, 'verbal-intelligence', 'Verbal Intelligence', 'Statements: All pilots are brave. No brave person is lazy. Some lazy persons are rich. Conclusions: I. No pilot is lazy. II. Some rich persons are not brave.', 'MCQ', 'HARD', 'Both I and II follow', 'Only I follows', 'Neither I nor II follows', 'Only II follows', 'A', 'Pilots ⊂ brave and brave ∩ lazy = ∅ → no pilot is lazy (I). The rich persons who are lazy cannot be brave → some rich persons are not brave (II).', null),
(56, 'verbal-intelligence', 'Verbal Intelligence', 'The price of an article is first increased by 20% and then decreased by 20%. The net change in the original price is:', 'MCQ', 'HARD', '4% decrease', '2% decrease', '4% increase', 'No change', 'A', '100 → 120 → 96. Net change = 4% decrease.', null),
(57, 'verbal-intelligence', 'Verbal Intelligence', 'A man sold an article for Rs. 1,080 at a loss of 10%. At what price should he sell it to gain 10%?', 'MCQ', 'HARD', 'Rs. 1,200', 'Rs. 1,296', 'Rs. 1,188', 'Rs. 1,320', 'D', 'CP = 1080 ÷ 0.9 = 1,200. Selling price for 10% gain = 1,200 × 1.1 = 1,320.', null),
(58, 'verbal-intelligence', 'Verbal Intelligence', 'A sum of money doubles itself in 8 years at simple interest. In how many years will it become three times?', 'MCQ', 'HARD', '20 years', '12 years', '16 years', '24 years', 'C', 'Interest equal to the principal takes 8 years; to make it triple the interest must be twice the principal: 2 × 8 = 16 years.', null),
(59, 'verbal-intelligence', 'Verbal Intelligence', 'Two trains of lengths 120 m and 180 m run on parallel tracks in opposite directions at 54 km/h and 36 km/h. How long will they take to cross each other?', 'MCQ', 'HARD', '12 seconds', '10 seconds', '15 seconds', '18 seconds', 'A', 'Relative speed = 90 km/h = 25 m/s. Distance = 300 m. Time = 300 ÷ 25 = 12 s.', null),
(60, 'verbal-intelligence', 'Verbal Intelligence', 'Pipes A and B can fill a tank in 10 hours and 15 hours respectively, and pipe C can empty it in 30 hours. If all three are opened together, how long will the tank take to fill?', 'MCQ', 'HARD', '7.5 hours', '8 hours', '9 hours', '6 hours', 'A', 'Net rate = 1/10 + 1/15 − 1/30 = 4/30 = 2/15 per hour → 7.5 hours.', null),
(61, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 1: Which figure is the odd one out?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'B', 'Three figures have 3 sides; the odd one has 4 sides.', '/images/full-mock-tests/first-full-mock-test/q061.png'),
(62, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 2: Which figure will come next in the series?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'D', 'The number of dots increases by 2 each time (1, 3, 5, 7 → 9).', '/images/full-mock-tests/first-full-mock-test/q062.png'),
(63, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 3: Which figure will come next in the series?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'A', 'The arrow turns 90° anticlockwise at every step.', '/images/full-mock-tests/first-full-mock-test/q063.png'),
(64, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 4: In every row, one rule connects the number of dots. Which figure completes the last row?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'B', 'In each row the first two figures'' dots added together give the third: 2 + 2 = 4.', '/images/full-mock-tests/first-full-mock-test/q064.png'),
(65, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 5: Which figure will come next in the series?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'C', 'The number of sides increases by 1 each time (3, 4, 5, 6 → 7).', '/images/full-mock-tests/first-full-mock-test/q065.png'),
(66, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 6: How many triangles are there in the figure?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'C', '3 line(s) from the apex give 5 points on the base line; every pair of base points with the apex makes a triangle: C(5,2) = 10.', '/images/full-mock-tests/first-full-mock-test/q066.png'),
(67, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 7: In every row, one rule connects the number of dots. Which figure completes the last row?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'D', 'In each row the first two figures'' dots added together give the third: 3 + 3 = 6.', '/images/full-mock-tests/first-full-mock-test/q067.png'),
(68, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 8: Which figure is the odd one out?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'C', 'Three figures have 3 sides; the odd one has 5 sides.', '/images/full-mock-tests/first-full-mock-test/q068.png'),
(69, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 9: Which figure will come next in the series?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'C', 'The shapes repeat in a cycle of three, while the shading alternates between unshaded and shaded at each step.', '/images/full-mock-tests/first-full-mock-test/q069.png'),
(70, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'A solid cube is painted red on all six faces and then cut into 27 equal small cubes (3 × 3 × 3). How many small cubes have exactly three faces painted?', 'NON_VERBAL', 'EASY', '1', '12', '6', '8', 'D', 'For an 3×3×3 cube: 3 faces → 8 (corners); 2 faces → 12(3−2) = 12; 1 face → 6(3−2)² = 6; no face → (3−2)³ = 1. Answer: 8.', null),
(71, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'A solid cube is painted red on all six faces and then cut into 27 equal small cubes (3 × 3 × 3). How many small cubes have exactly one face painted?', 'NON_VERBAL', 'EASY', '6', '1', '8', '12', 'A', 'For an 3×3×3 cube: 3 faces → 8 (corners); 2 faces → 12(3−2) = 12; 1 face → 6(3−2)² = 6; no face → (3−2)³ = 1. Answer: 6.', null),
(72, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 12: Which figure will come next in the series?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'C', 'The arrow turns 90° clockwise at every step.', '/images/full-mock-tests/first-full-mock-test/q072.png'),
(73, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 13: Which figure will come next in the series?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'C', 'The number of sides increases by 1 each time (3, 4, 5, 6 → 7).', '/images/full-mock-tests/first-full-mock-test/q073.png'),
(74, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 14: Which figure will come next in the series?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'C', 'The number of dots increases by 2 each time (1, 3, 5, 7 → 9).', '/images/full-mock-tests/first-full-mock-test/q074.png'),
(75, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 15: Which figure will come next in the series?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'C', 'The arrow turns 90° clockwise at every step.', '/images/full-mock-tests/first-full-mock-test/q075.png'),
(76, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 16: Which figure is the odd one out?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'A', 'Three figures are shaded; the odd one is unshaded.', '/images/full-mock-tests/first-full-mock-test/q076.png'),
(77, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 17: Which figure is the odd one out?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'A', 'Three figures are shaded; the odd one is unshaded.', '/images/full-mock-tests/first-full-mock-test/q077.png'),
(78, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 18: How many triangles are there in the figure?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'A', '4 line(s) from the apex give 6 points on the base line; every pair of base points with the apex makes a triangle: C(6,2) = 15.', '/images/full-mock-tests/first-full-mock-test/q078.png'),
(79, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 19: Which figure is the odd one out?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'C', 'Three figures have 3 sides; the odd one has 4 sides.', '/images/full-mock-tests/first-full-mock-test/q079.png'),
(80, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 20: How many triangles are there in the figure?', 'NON_VERBAL', 'EASY', 'A', 'B', 'C', 'D', 'B', '2 line(s) from the apex give 4 points on the base line; every pair of base points with the apex makes a triangle: C(4,2) = 6.', '/images/full-mock-tests/first-full-mock-test/q080.png'),
(81, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 21: The figure is a grid of 3 rows × 3 columns of equal small squares. How many squares (of all sizes) can be counted in it?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'C', 'Count squares of every size: 9 + 4 + 1 = 14.', '/images/full-mock-tests/first-full-mock-test/q081.png'),
(82, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 22: Each row and each column contains every shape once and every shading once. Which figure completes the grid?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'B', 'Row 3 already has two of the three shapes and two of the three shadings; the missing shape and the missing shading must complete the row (and the column).', '/images/full-mock-tests/first-full-mock-test/q082.png'),
(83, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 23: Each row and each column contains every shape once and every shading once. Which figure completes the grid?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'B', 'Row 3 already has two of the three shapes and two of the three shadings; the missing shape and the missing shading must complete the row (and the column).', '/images/full-mock-tests/first-full-mock-test/q083.png'),
(84, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 24: Select the mirror image (the mirror is the dashed line on the right) of the given figure.', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'D', 'A mirror image on the right is a left ↔ right flip: the column nearest the mirror stays nearest the mirror.', '/images/full-mock-tests/first-full-mock-test/q084.png'),
(85, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 25: Select the mirror image (the mirror is the dashed line on the right) of the given figure.', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'D', 'A mirror image on the right is a left ↔ right flip: the column nearest the mirror stays nearest the mirror.', '/images/full-mock-tests/first-full-mock-test/q085.png'),
(86, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 26: A square sheet of paper is folded once in half down the middle (left half folded over the right half). A hole is punched in the folded paper as shown. Which figure shows the paper when it is unfolded?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'B', 'Unfolding reflects the hole across the fold line (vertical centre line): one hole becomes two holes at the same height, one on each side of the fold.', '/images/full-mock-tests/first-full-mock-test/q086.png'),
(87, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 27: The figure is a grid of 2 rows × 2 columns of equal small squares. How many rectangles of all sizes (including squares) are there in it?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'D', 'Choose 2 of 3 horizontal lines and 2 of 3 vertical lines: C(3,2) × C(3,2) = 3 × 3 = 9.', '/images/full-mock-tests/first-full-mock-test/q087.png'),
(88, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 28: Three of the figures are the same shape turned to different positions. Which figure is the odd one out (a mirror image of the others)?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'D', 'Three figures can be matched by simple rotation. The odd one is a flipped (mirror) version and can never be obtained by rotating the others.', '/images/full-mock-tests/first-full-mock-test/q088.png'),
(89, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 29: The figure is a grid of 2 rows × 3 columns of equal small squares. How many rectangles of all sizes (including squares) are there in it?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'C', 'Choose 2 of 3 horizontal lines and 2 of 4 vertical lines: C(3,2) × C(4,2) = 3 × 6 = 18.', '/images/full-mock-tests/first-full-mock-test/q089.png'),
(90, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 30: The figure is a grid of 2 rows × 2 columns of equal small squares. How many squares (of all sizes) can be counted in it?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'B', 'Count squares of every size: 4 + 1 = 5.', '/images/full-mock-tests/first-full-mock-test/q090.png'),
(91, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 31: Which figure will come next in the series?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'A', 'The arrow turns 135° clockwise at every step.', '/images/full-mock-tests/first-full-mock-test/q091.png'),
(92, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 32: Select the mirror image (the mirror is the dashed line on the right) of the given figure.', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'A', 'A mirror image on the right is a left ↔ right flip: the column nearest the mirror stays nearest the mirror.', '/images/full-mock-tests/first-full-mock-test/q092.png'),
(93, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 33: A square sheet of paper is folded once in half down the middle (left half folded over the right half). A hole is punched in the folded paper as shown. Which figure shows the paper when it is unfolded?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'B', 'Unfolding reflects the hole across the fold line (vertical centre line): one hole becomes two holes at the same height, one on each side of the fold.', '/images/full-mock-tests/first-full-mock-test/q093.png'),
(94, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 34: Three of the figures are the same shape turned to different positions. Which figure is the odd one out (a mirror image of the others)?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'B', 'Three figures can be matched by simple rotation. The odd one is a flipped (mirror) version and can never be obtained by rotating the others.', '/images/full-mock-tests/first-full-mock-test/q094.png'),
(95, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 35: A square sheet of paper is folded once in half down the middle (left half folded over the right half). A hole is punched in the folded paper as shown. Which figure shows the paper when it is unfolded?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'D', 'Unfolding reflects the hole across the fold line (vertical centre line): one hole becomes two holes at the same height, one on each side of the fold.', '/images/full-mock-tests/first-full-mock-test/q095.png'),
(96, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 36: Three of the figures are the same shape turned to different positions. Which figure is the odd one out (a mirror image of the others)?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'D', 'Three figures can be matched by simple rotation. The odd one is a flipped (mirror) version and can never be obtained by rotating the others.', '/images/full-mock-tests/first-full-mock-test/q096.png'),
(97, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 37: Which figure will come next in the series?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'B', 'The shaded square moves 1 position(s) clockwise around the outer ring each step.', '/images/full-mock-tests/first-full-mock-test/q097.png'),
(98, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 38: Which figure will come next in the series?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'D', 'The arrow turns 45° anticlockwise at every step.', '/images/full-mock-tests/first-full-mock-test/q098.png'),
(99, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 39: Which figure will come next in the series?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'D', 'The shaded square moves 1 position(s) clockwise around the outer ring each step.', '/images/full-mock-tests/first-full-mock-test/q099.png'),
(100, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 40: In every row, one rule connects the number of dots. Which figure completes the last row?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'A', 'In each row the second figure''s dots subtracted from the first give the third: 6 − 3 = 3.', '/images/full-mock-tests/first-full-mock-test/q100.png'),
(101, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 41: Which figure will come next in the series?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'B', 'The shaded square moves 2 position(s) anticlockwise around the outer ring each step.', '/images/full-mock-tests/first-full-mock-test/q101.png'),
(102, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 42: Each row and each column contains every shape once and every shading once. Which figure completes the grid?', 'NON_VERBAL', 'MEDIUM', 'A', 'B', 'C', 'D', 'D', 'Row 3 already has two of the three shapes and two of the three shadings; the missing shape and the missing shading must complete the row (and the column).', '/images/full-mock-tests/first-full-mock-test/q102.png'),
(103, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 43: Select the water image (the reflection in the water below the figure) of the given figure.', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'B', 'A water image is turned upside-down (top ↔ bottom) while left and right stay as they are.', '/images/full-mock-tests/first-full-mock-test/q103.png'),
(104, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 44: The figure is a grid of 3 rows × 4 columns of equal small squares. How many rectangles of all sizes (including squares) are there in it?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'B', 'Choose 2 of 4 horizontal lines and 2 of 5 vertical lines: C(4,2) × C(5,2) = 6 × 10 = 60.', '/images/full-mock-tests/first-full-mock-test/q104.png'),
(105, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 45: Figure A is changed into Figure B by a rule. Apply the same rule to Figure C. (First figure : second figure :: third figure : ?)', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'D', 'The first figure is rotated 90° anticlockwise to give the second. The same change applied to the third figure gives the answer.', '/images/full-mock-tests/first-full-mock-test/q105.png'),
(106, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 46: Which figure will come next in the series?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'A', 'Two changes happen together at every step: the figure turns 90° clockwise and its shading is reversed (black ↔ white).', '/images/full-mock-tests/first-full-mock-test/q106.png'),
(107, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 47: Three of the figures are the same shape turned to different positions. Which figure is the odd one out (a mirror image of the others)?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'D', 'Three figures can be matched by simple rotation. The odd one is a flipped (mirror) version and can never be obtained by rotating the others.', '/images/full-mock-tests/first-full-mock-test/q107.png'),
(108, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 48: Three of the figures are the same shape turned to different positions. Which figure is the odd one out (a mirror image of the others)?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'B', 'Three figures can be matched by simple rotation. The odd one is a flipped (mirror) version and can never be obtained by rotating the others.', '/images/full-mock-tests/first-full-mock-test/q108.png'),
(109, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 49: Which figure will come next in the series?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'C', 'Two changes happen together at every step: the figure turns 90° clockwise and its shading is reversed (black ↔ white).', '/images/full-mock-tests/first-full-mock-test/q109.png'),
(110, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 50: A square sheet is folded in half vertically (left over right) and then in half horizontally (bottom over top), so the folded paper is one quarter of the original. One hole is punched in the folded paper as shown. Which figure shows the paper when it is fully unfolded?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'C', 'Each of the two folds doubles the holes: the hole is reflected across the vertical centre line and across the horizontal centre line, giving four holes at the corners of a rectangle.', '/images/full-mock-tests/first-full-mock-test/q110.png'),
(111, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 51: Two squares are shaded in each figure. Which figure will come next in the series?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'A', 'One shaded square moves 1 step clockwise and the other moves 1 step anticlockwise around the outer ring each time.', '/images/full-mock-tests/first-full-mock-test/q111.png'),
(112, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 52: Which figure will come next in the series?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'A', 'Two changes happen together at every step: the figure turns 90° clockwise and its shading is reversed (black ↔ white).', '/images/full-mock-tests/first-full-mock-test/q112.png'),
(113, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 53: Figure A is changed into Figure B by a rule. Apply the same rule to Figure C. (First figure : second figure :: third figure : ?)', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'C', 'The first figure is rotated 90° clockwise and shading reversed to give the second. The same change applied to the third figure gives the answer.', '/images/full-mock-tests/first-full-mock-test/q113.png'),
(114, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 54: Select the water image (the reflection in the water below the figure) of the given figure.', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'C', 'A water image is turned upside-down (top ↔ bottom) while left and right stay as they are.', '/images/full-mock-tests/first-full-mock-test/q114.png'),
(115, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 55: Figure A is changed into Figure B by a rule. Apply the same rule to Figure C. (First figure : second figure :: third figure : ?)', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'A', 'The first figure is rotated 90° anticlockwise to give the second. The same change applied to the third figure gives the answer.', '/images/full-mock-tests/first-full-mock-test/q115.png'),
(116, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 56: Figure A is changed into Figure B by a rule. Apply the same rule to Figure C. (First figure : second figure :: third figure : ?)', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'A', 'The first figure is flipped left ↔ right to give the second. The same change applied to the third figure gives the answer.', '/images/full-mock-tests/first-full-mock-test/q116.png'),
(117, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 57: A square sheet is folded in half vertically (left over right) and then in half horizontally (bottom over top), so the folded paper is one quarter of the original. One hole is punched in the folded paper as shown. Which figure shows the paper when it is fully unfolded?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'D', 'Each of the two folds doubles the holes: the hole is reflected across the vertical centre line and across the horizontal centre line, giving four holes at the corners of a rectangle.', '/images/full-mock-tests/first-full-mock-test/q117.png'),
(118, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 58: Two squares are shaded in each figure. Which figure will come next in the series?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'A', 'One shaded square moves 1 step clockwise and the other moves 1 step anticlockwise around the outer ring each time.', '/images/full-mock-tests/first-full-mock-test/q118.png'),
(119, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 59: A square sheet is folded in half vertically (left over right) and then in half horizontally (bottom over top), so the folded paper is one quarter of the original. One hole is punched in the folded paper as shown. Which figure shows the paper when it is fully unfolded?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'B', 'Each of the two folds doubles the holes: the hole is reflected across the vertical centre line and across the horizontal centre line, giving four holes at the corners of a rectangle.', '/images/full-mock-tests/first-full-mock-test/q119.png'),
(120, 'non-verbal-intelligence', 'Non-Verbal Intelligence', 'Non-verbal question 60: Which figure will come next in the series?', 'NON_VERBAL', 'HARD', 'A', 'B', 'C', 'D', 'A', 'Two changes happen together at every step: the figure turns 90° clockwise and its shading is reversed (black ↔ white).', '/images/full-mock-tests/first-full-mock-test/q120.png'),
(121, 'physics', 'Physics', 'The dimensions of force are:', 'MCQ', 'EASY', '[ML²T⁻²]', '[ML⁻¹T⁻²]', '[MLT⁻¹]', '[MLT⁻²]', 'D', 'F = ma = kg · m/s² → [M][L][T⁻²].', null),
(122, 'physics', 'Physics', 'Which of the following is a vector quantity?', 'MCQ', 'EASY', 'Mass', 'Distance', 'Displacement', 'Speed', 'C', 'Displacement has both magnitude and direction; distance, speed and mass are scalars.', null),
(123, 'physics', 'Physics', 'The time period of a simple pendulum of length 2.45 m at a place where g = 9.8 m s⁻² is:', 'MCQ', 'EASY', '6.28 s', '3.14 s', '1.57 s', '9.86 s', 'B', 'T = 2π√(l/g) = 2π√(2.45/9.8) = 2π(0.5) = π ≈ 3.14 s.', null),
(124, 'physics', 'Physics', 'What force is required to produce an acceleration of 4 m s⁻² in a body of mass 5 kg?', 'MCQ', 'EASY', '9 N', '40 N', '1.25 N', '20 N', 'D', 'F = ma = 5 × 4 = 20 N.', null),
(125, 'physics', 'Physics', 'The kinetic energy of a 2 kg body moving with a speed of 3 m s⁻¹ is:', 'MCQ', 'EASY', '9 J', '12 J', '18 J', '6 J', 'A', 'K.E. = ½mv² = ½ × 2 × 9 = 9 J.', null),
(126, 'physics', 'Physics', 'How much work is done in lifting a 10 kg mass through a height of 5 m? (g = 9.8 m s⁻²)', 'MCQ', 'EASY', '245 J', '490 J', '50 J', '98 J', 'B', 'W = mgh = 10 × 9.8 × 5 = 490 J.', null),
(127, 'physics', 'Physics', 'A wave has a time period of 0.02 s. Its frequency is:', 'MCQ', 'EASY', '50 Hz', '200 Hz', '0.02 Hz', '20 Hz', 'A', 'f = 1/T = 1/0.02 = 50 Hz.', null),
(128, 'physics', 'Physics', 'A current of how much will flow through a 4 Ω resistor connected across a 12 V battery?', 'MCQ', 'EASY', '0.33 A', '48 A', '8 A', '3 A', 'D', 'I = V/R = 12/4 = 3 A (Ohm''s law).', null),
(129, 'physics', 'Physics', 'Two resistors of 6 Ω and 3 Ω are connected in parallel. Their equivalent resistance is:', 'MCQ', 'EASY', '9 Ω', '18 Ω', '2 Ω', '4.5 Ω', 'C', '1/R = 1/6 + 1/3 = 3/6 → R = 2 Ω.', null),
(130, 'physics', 'Physics', 'The output of a NOR gate is 1 (HIGH) only when:', 'MCQ', 'EASY', 'Both inputs are 0', 'Both inputs are 1', 'Any one input is 1', 'Inputs are different', 'A', 'NOR = NOT(OR). OR is 0 only when both inputs are 0, so NOR is 1 only then.', null),
(131, 'physics', 'Physics', 'A ball is thrown at 19.6 m s⁻¹ at an angle of 45° to the horizontal. Its horizontal range is (g = 9.8 m s⁻²):', 'MCQ', 'MEDIUM', '39.2 m', '19.6 m', '78.4 m', '27.7 m', 'A', 'R = v² sin 2θ / g = (19.6)² × 1 / 9.8 = 39.2 m (maximum range at 45°).', null),
(132, 'physics', 'Physics', 'A 2 kg body moving at 6 m s⁻¹ collides with a 4 kg body at rest and they stick together. Their common velocity is:', 'MCQ', 'MEDIUM', '2 m s⁻¹', '3 m s⁻¹', '1.5 m s⁻¹', '4 m s⁻¹', 'A', 'Momentum conservation: 2 × 6 = (2 + 4)v → v = 2 m s⁻¹.', null),
(133, 'physics', 'Physics', 'A 0.5 kg stone is whirled in a horizontal circle of radius 0.4 m with a speed of 4 m s⁻¹. The centripetal force on it is:', 'MCQ', 'MEDIUM', '20 N', '32 N', '5 N', '8 N', 'A', 'F = mv²/r = 0.5 × 16 / 0.4 = 20 N.', null),
(134, 'physics', 'Physics', 'The escape velocity from the surface of the earth is approximately:', 'MCQ', 'MEDIUM', '7.9 km s⁻¹', '9.8 km s⁻¹', '11.2 km s⁻¹', '15.0 km s⁻¹', 'C', 'v_esc = √(2gR) ≈ 11.2 km/s (7.9 km/s is the orbital velocity near the surface).', null),
(135, 'physics', 'Physics', 'Water flows at 2 m s⁻¹ through a pipe of diameter 4 cm which narrows to a diameter of 2 cm. The speed in the narrow part is:', 'MCQ', 'MEDIUM', '16 m s⁻¹', '4 m s⁻¹', '8 m s⁻¹', '6 m s⁻¹', 'C', 'Equation of continuity: A₁v₁ = A₂v₂. Area ∝ d², so area ratio = 4 and v₂ = 4 × 2 = 8 m/s.', null),
(136, 'physics', 'Physics', 'A 2 kg mass attached to a spring of force constant 200 N m⁻¹ executes simple harmonic motion. Its time period is:', 'MCQ', 'MEDIUM', '0.31 s', '0.63 s', '6.28 s', '1.57 s', 'B', 'T = 2π√(m/k) = 2π√(2/200) = 2π × 0.1 = 0.628 s ≈ 0.63 s.', null),
(137, 'physics', 'Physics', 'A gas at 27 °C is heated at constant pressure until its volume doubles. The final temperature is:', 'MCQ', 'MEDIUM', '54 °C', '300 °C', '600 °C', '327 °C', 'D', 'Charles'' law: V/T = constant. T₂ = 2 × 300 K = 600 K = 327 °C.', null),
(138, 'physics', 'Physics', 'The efficiency of a Carnot engine working between 600 K and 300 K is:', 'MCQ', 'MEDIUM', '50%', '25%', '75%', '100%', 'A', 'η = 1 − T₂/T₁ = 1 − 300/600 = 0.5 = 50%.', null),
(139, 'physics', 'Physics', 'Two point charges of 1 μC each are placed 0.3 m apart in air. The force between them is (k = 9 × 10⁹ N m² C⁻²):', 'MCQ', 'MEDIUM', '0.03 N', '9 N', '0.1 N', '1 N', 'C', 'F = kq₁q₂/r² = 9×10⁹ × 10⁻¹² / 0.09 = 0.1 N (repulsive).', null),
(140, 'physics', 'Physics', 'The energy stored in a 10 μF capacitor charged to 100 V is:', 'MCQ', 'MEDIUM', '0.5 J', '0.005 J', '1.0 J', '0.05 J', 'D', 'U = ½CV² = ½ × 10×10⁻⁶ × 10⁴ = 0.05 J.', null),
(141, 'physics', 'Physics', 'The power dissipated in a 5 Ω resistor carrying a current of 2 A is:', 'MCQ', 'MEDIUM', '20 W', '50 W', '10 W', '2.5 W', 'A', 'P = I²R = 4 × 5 = 20 W.', null),
(142, 'physics', 'Physics', 'A straight conductor 0.5 m long carries 4 A and is placed perpendicular to a magnetic field of 0.5 T. The force on it is:', 'MCQ', 'MEDIUM', '4 N', '1 N', '0.25 N', '2 N', 'B', 'F = BIL sin θ = 0.5 × 4 × 0.5 × 1 = 1 N.', null),
(143, 'physics', 'Physics', 'A transformer has 200 turns in the primary and 1000 turns in the secondary. If the primary is connected to 220 V a.c., the secondary voltage is:', 'MCQ', 'HARD', '44 V', '1100 V', '220 V', '4400 V', 'B', 'V_s/V_p = N_s/N_p → V_s = 220 × 1000/200 = 1100 V (step-up).', null),
(144, 'physics', 'Physics', 'The peak value of an alternating voltage is 311 V. Its r.m.s. value is approximately:', 'MCQ', 'HARD', '311 V', '220 V', '156 V', '440 V', 'B', 'V_rms = V₀/√2 = 311/1.414 ≈ 220 V.', null),
(145, 'physics', 'Physics', 'Light of photon energy 5 eV falls on a metal of work function 2 eV. The maximum kinetic energy of the emitted photoelectrons is:', 'MCQ', 'HARD', '7 eV', '2.5 eV', '2 eV', '3 eV', 'D', 'Einstein''s equation: K.E.max = hf − φ = 5 − 2 = 3 eV.', null),
(146, 'physics', 'Physics', 'The energy of a photon of wavelength 500 nm is approximately (hc = 1240 eV·nm):', 'MCQ', 'HARD', '6.20 eV', '1.24 eV', '2.48 eV', '3.10 eV', 'C', 'E = hc/λ = 1240 / 500 = 2.48 eV.', null),
(147, 'physics', 'Physics', 'In the hydrogen atom, the energy of the photon emitted when an electron jumps from the third orbit (n = 3) to the second orbit (n = 2) is:', 'MCQ', 'HARD', '10.2 eV', '3.40 eV', '1.89 eV', '12.1 eV', 'C', 'ΔE = 13.6 (1/2² − 1/3²) = 13.6 × 5/36 = 1.89 eV (first line of the Balmer series).', null),
(148, 'physics', 'Physics', 'A radioactive substance has a half-life of 4 days. The fraction of the original amount left after 12 days is:', 'MCQ', 'HARD', '1/4', '1/8', '1/3', '1/6', 'B', '12 days = 3 half-lives → (1/2)³ = 1/8.', null),
(149, 'physics', 'Physics', 'In Young''s double-slit experiment, light of wavelength 600 nm is used, the slit separation is 0.4 mm and the screen is 2 m away. The fringe spacing is:', 'MCQ', 'HARD', '6 mm', '3 mm', '0.3 mm', '1.2 mm', 'B', 'Δy = λL/d = (600×10⁻⁹ × 2)/(0.4×10⁻³) = 3×10⁻³ m = 3 mm.', null),
(150, 'physics', 'Physics', 'The mass defect of a nucleus is 0.002 u. The binding energy is approximately (1 u = 931.5 MeV):', 'MCQ', 'HARD', '18.6 MeV', '186 MeV', '0.93 MeV', '1.86 MeV', 'D', 'E = Δm × 931.5 = 0.002 × 931.5 = 1.863 MeV.', null),
(151, 'english', 'English', 'Choose the word closest in meaning to ABUNDANT.', 'MCQ', 'EASY', 'Rare', 'Scarce', 'Plentiful', 'Limited', 'C', 'Abundant means existing in large quantities — plentiful.', null),
(152, 'english', 'English', 'Choose the word opposite in meaning to BRAVE.', 'MCQ', 'EASY', 'Fearless', 'Cowardly', 'Heroic', 'Bold', 'B', 'Brave means courageous; cowardly is the opposite.', null),
(153, 'english', 'English', 'Choose the correct option: She ______ to school every day.', 'MCQ', 'EASY', 'gone', 'goes', 'go', 'going', 'B', 'A singular third-person subject takes the present-tense verb with -s/-es: goes.', null),
(154, 'english', 'English', 'Choose the correct option: Neither of the boys ______ present.', 'MCQ', 'EASY', 'were', 'have been', 'was', 'are', 'C', '''Neither'' is singular and takes a singular verb: was.', null),
(155, 'english', 'English', 'Choose the correct preposition: He is very good ______ mathematics.', 'MCQ', 'EASY', 'in', 'on', 'at', 'with', 'C', 'The correct collocation is ''good at'' a subject.', null),
(156, 'english', 'English', 'Select the correctly spelled word.', 'MCQ', 'EASY', 'Neccessary', 'Necessary', 'Necesary', 'Necessarry', 'B', 'Necessary has one c and two s''s.', null),
(157, 'english', 'English', 'One word for: a person who loves mankind and helps others.', 'MCQ', 'EASY', 'Misanthrope', 'Philanthropist', 'Pessimist', 'Egoist', 'B', 'A philanthropist works for the welfare of humanity; a misanthrope hates people.', null),
(158, 'english', 'English', 'What does the idiom "to beat about the bush" mean?', 'MCQ', 'EASY', 'To work very hard', 'To hit someone hard', 'To avoid coming to the point directly', 'To hunt animals', 'C', 'Beating about the bush means talking around a topic without getting to the point.', null),
(159, 'english', 'English', 'Choose the correct article: He is ______ honest man.', 'MCQ', 'EASY', 'the', 'no article is needed', 'an', 'a', 'C', '''Honest'' begins with a vowel sound (silent h), so ''an'' is used.', null),
(160, 'english', 'English', 'What is the plural of "phenomenon"?', 'MCQ', 'EASY', 'Phenomena', 'Phenomenes', 'Phenomenas', 'Phenomenons', 'A', 'Phenomenon is of Greek origin; its plural is phenomena.', null),
(161, 'english', 'English', 'Choose the word closest in meaning to CANDID.', 'MCQ', 'MEDIUM', 'Cunning', 'Frank', 'Sweet', 'Secretive', 'B', 'Candid means open and honest — frank.', null),
(162, 'english', 'English', 'Choose the word opposite in meaning to BENEVOLENT.', 'MCQ', 'MEDIUM', 'Malevolent', 'Generous', 'Charitable', 'Kind', 'A', 'Benevolent means well-meaning and kind; malevolent means wishing harm.', null),
(163, 'english', 'English', 'One word for: government by a small group of people.', 'MCQ', 'MEDIUM', 'Democracy', 'Monarchy', 'Anarchy', 'Oligarchy', 'D', 'Oligarchy = rule by a few; monarchy = rule by one; anarchy = no government.', null),
(164, 'english', 'English', 'What does the idiom "a blessing in disguise" mean?', 'MCQ', 'MEDIUM', 'A hidden gift', 'Something that seems bad but turns out to be good', 'A disguised person', 'A secret prayer', 'B', 'It is an apparent misfortune that eventually brings benefit.', null),
(165, 'english', 'English', 'Change into passive voice: "The teacher punished the boy."', 'MCQ', 'MEDIUM', 'The boy is punished by the teacher.', 'The boy has been punished by the teacher.', 'The teacher was punished by the boy.', 'The boy was punished by the teacher.', 'D', 'Simple past active → was/were + past participle in the passive.', null),
(166, 'english', 'English', 'Change into indirect speech: He said, "I am happy."', 'MCQ', 'MEDIUM', 'He said that he is happy.', 'He said that he was happy.', 'He said that I was happy.', 'He said that he has been happy.', 'B', 'In reported speech the present tense changes to past (am → was) and ''I'' becomes ''he''.', null),
(167, 'english', 'English', 'Choose the correct option: By the time we reached the station, the train ______.', 'MCQ', 'MEDIUM', 'had left', 'left', 'has left', 'was leaving', 'A', 'Past perfect (had left) shows the earlier of two past actions.', null),
(168, 'english', 'English', 'Choose the correct sentence.', 'MCQ', 'MEDIUM', 'He didn''t liked tea.', 'He don''t like tea.', 'He not like tea.', 'He doesn''t like tea.', 'D', 'A third-person singular subject takes ''doesn''t'' with the base verb.', null),
(169, 'english', 'English', 'Choose the correct preposition: She is married ______ a doctor.', 'MCQ', 'MEDIUM', 'to', 'from', 'with', 'by', 'A', 'The correct collocation is ''married to''.', null),
(170, 'english', 'English', 'Choose the correct option: If I ______ you, I would accept the offer.', 'MCQ', 'MEDIUM', 'were', 'was', 'am', 'will be', 'A', 'Second conditional (unreal present) uses ''were'' for all persons.', null),
(171, 'english', 'English', 'Choose the word closest in meaning to OBSOLETE.', 'MCQ', 'MEDIUM', 'Necessary', 'Modern', 'Outdated', 'Fragile', 'C', 'Obsolete means no longer in use — outdated.', null),
(172, 'english', 'English', 'Select the correctly spelled word.', 'MCQ', 'MEDIUM', 'Accommodation', 'Accomodation', 'Acommodation', 'Acomodation', 'A', 'Accommodation has double c and double m.', null),
(173, 'english', 'English', 'Choose the word closest in meaning to EPHEMERAL.', 'MCQ', 'HARD', 'Short-lived', 'Eternal', 'Fragrant', 'Heavenly', 'A', 'Ephemeral means lasting for a very short time.', null),
(174, 'english', 'English', 'Choose the word opposite in meaning to VERBOSE.', 'MCQ', 'HARD', 'Fluent', 'Wordy', 'Talkative', 'Concise', 'D', 'Verbose means using too many words; concise means brief and to the point.', null),
(175, 'english', 'English', 'One word for: one who is present everywhere.', 'MCQ', 'HARD', 'Omnivorous', 'Omnipotent', 'Omniscient', 'Omnipresent', 'D', 'Omnipresent = present everywhere; omniscient = all-knowing; omnipotent = all-powerful.', null),
(176, 'english', 'English', 'What does the idiom "to bell the cat" mean?', 'MCQ', 'HARD', 'To punish a cat', 'To make a lot of noise', 'To tell a secret', 'To take on a risky task for the common good', 'D', 'From the fable of the mice: to undertake a dangerous task on behalf of a group.', null),
(177, 'english', 'English', 'Choose the correct sentence.', 'MCQ', 'HARD', 'Hardly had he reached the station when the train left.', 'Hardly did he reached the station when the train left.', 'Hardly he had reached the station when the train left.', 'Hardly had he reached the station than the train left.', 'A', '''Hardly … when'' is the correct pair, with inversion (had he reached) after ''hardly''.', null),
(178, 'english', 'English', 'Choose the correct preposition: He insisted ______ paying the bill.', 'MCQ', 'HARD', 'to', 'on', 'for', 'at', 'B', 'The correct collocation is ''insist on''.', null),
(179, 'english', 'English', 'Choose the correct option: Each of the students ______ given a certificate.', 'MCQ', 'HARD', 'have been', 'are', 'was', 'were', 'C', '''Each'' is singular, so it takes the singular verb ''was''.', null),
(180, 'english', 'English', 'Choose the correct word: The new policy will ______ everyone in the country.', 'MCQ', 'HARD', 'effect', 'effects', 'afect', 'affect', 'D', '''Affect'' is the verb meaning to influence; ''effect'' is usually the noun (result).', null),
(181, 'general-knowledge', 'General Knowledge', 'The Pakistan (Lahore) Resolution was passed on:', 'MCQ', 'EASY', '6 December 1945', '23 March 1940', '30 December 1906', '14 August 1947', 'B', 'The Lahore Resolution was adopted at the Muslim League session at Minto Park, Lahore, on 23 March 1940.', null),
(182, 'general-knowledge', 'General Knowledge', 'Who was the first Governor-General of Pakistan?', 'MCQ', 'EASY', 'Khawaja Nazimuddin', 'Ghulam Muhammad', 'Liaquat Ali Khan', 'Quaid-e-Azam Muhammad Ali Jinnah', 'D', 'Jinnah took oath as the first Governor-General on 15 August 1947.', null),
(183, 'general-knowledge', 'General Knowledge', 'The highest mountain peak in Pakistan is:', 'MCQ', 'EASY', 'Nanga Parbat', 'Broad Peak', 'K2', 'Tirich Mir', 'C', 'K2 (Godwin-Austen) in the Karakoram is the highest peak in Pakistan and second highest in the world.', null),
(184, 'general-knowledge', 'General Knowledge', 'The longest river of Pakistan is:', 'MCQ', 'EASY', 'Sutlej', 'Jhelum', 'Indus', 'Chenab', 'C', 'The Indus (about 3,000 km) is the longest river in Pakistan.', null),
(185, 'general-knowledge', 'General Knowledge', 'The Khyber Pass connects Pakistan with:', 'MCQ', 'EASY', 'India', 'Afghanistan', 'China', 'Iran', 'B', 'The Khyber Pass links Peshawar (Pakistan) with Jalalabad/Kabul side of Afghanistan.', null),
(186, 'general-knowledge', 'General Knowledge', 'The Pakistan Military Academy (PMA) is located at:', 'MCQ', 'EASY', 'Quetta', 'Kohat', 'Kakul, Abbottabad', 'Rawalpindi', 'C', 'PMA Kakul is in Abbottabad, Khyber Pakhtunkhwa.', null),
(187, 'general-knowledge', 'General Knowledge', 'Who was the first Prime Minister of Pakistan?', 'MCQ', 'EASY', 'Liaquat Ali Khan', 'Feroz Khan Noon', 'H. S. Suhrawardy', 'Chaudhry Muhammad Ali', 'A', 'Liaquat Ali Khan served from 1947 until his assassination in 1951.', null),
(188, 'general-knowledge', 'General Knowledge', 'Allama Iqbal presented the idea of a separate Muslim state in North-West India in his presidential address at Allahabad in:', 'MCQ', 'MEDIUM', '1920', '1937', '1940', '1930', 'D', 'The Allahabad Address was delivered at the Muslim League session in December 1930.', null),
(189, 'general-knowledge', 'General Knowledge', 'Tarbela Dam is built on the river:', 'MCQ', 'MEDIUM', 'Indus', 'Kabul', 'Jhelum', 'Chenab', 'A', 'Tarbela, the largest earth-filled dam in the world, is on the Indus in Khyber Pakhtunkhwa.', null),
(190, 'general-knowledge', 'General Knowledge', 'Who was the first recipient of the Nishan-e-Haider?', 'MCQ', 'MEDIUM', 'Captain Raja Muhammad Sarwar Shaheed', 'Major Tufail Muhammad Shaheed', 'Havaldar Lalak Jan Shaheed', 'Major Aziz Bhatti Shaheed', 'A', 'Captain Raja Muhammad Sarwar (1948 Kashmir operations) was the first recipient of Pakistan''s highest gallantry award.', null),
(191, 'general-knowledge', 'General Knowledge', 'The motto of the Pakistan Army is:', 'MCQ', 'MEDIUM', 'Unity, Faith, Discipline', 'Faith, Unity, Sacrifice', 'Iman, Taqwa, Jihad fi Sabilillah', 'Duty, Honour, Country', 'C', 'The Army motto is ''Iman, Taqwa, Jihad fi Sabilillah'' (Faith, Piety, Striving in the Way of Allah).', null),
(192, 'general-knowledge', 'General Knowledge', 'The United Nations Organization was founded in:', 'MCQ', 'MEDIUM', '1945', '1950', '1948', '1919', 'A', 'The UN came into existence on 24 October 1945 after the Second World War.', null),
(193, 'general-knowledge', 'General Knowledge', 'Which is the largest country of the world by area?', 'MCQ', 'MEDIUM', 'United States', 'Russia', 'China', 'Canada', 'B', 'Russia is the largest country by area.', null),
(194, 'general-knowledge', 'General Knowledge', 'The headquarters of the Organisation of Islamic Cooperation (OIC) is in:', 'MCQ', 'MEDIUM', 'Riyadh', 'Jeddah', 'Makkah', 'Cairo', 'B', 'The OIC Secretariat is in Jeddah, Saudi Arabia.', null),
(195, 'general-knowledge', 'General Knowledge', 'Pakistan conducted its nuclear tests at Chagai on:', 'MCQ', 'HARD', '28 May 1999', '11 May 1998', '28 May 1998', '14 August 1998', 'C', 'Pakistan carried out its tests on 28 May 1998, observed as Youm-e-Takbeer.', null),
(196, 'general-knowledge', 'General Knowledge', 'Pakistan''s first Constitution was enforced in:', 'MCQ', 'HARD', '1947', '1973', '1962', '1956', 'D', 'The first Constitution was enforced on 23 March 1956; the 1962 and 1973 Constitutions followed.', null),
(197, 'general-knowledge', 'General Knowledge', 'The Battle of Badr was fought in the year:', 'MCQ', 'HARD', '2 A.H.', '1 A.H.', '3 A.H.', '5 A.H.', 'A', 'Badr was fought on 17 Ramadan, 2 A.H. (624 CE); Uhud 3 A.H.; Khandaq 5 A.H.', null),
(198, 'general-knowledge', 'General Knowledge', 'Which Nishan-e-Haider recipient belonged to the Pakistan Air Force?', 'MCQ', 'HARD', 'Major Muhammad Akram Shaheed', 'Major Shabbir Sharif Shaheed', 'Captain Karnal Sher Khan Shaheed', 'Pilot Officer Rashid Minhas Shaheed', 'D', 'Pilot Officer Rashid Minhas (1971) is the PAF''s Nishan-e-Haider recipient; the others served in the Army.', null),
(199, 'general-knowledge', 'General Knowledge', 'The South Asian Association for Regional Cooperation (SAARC) was founded in:', 'MCQ', 'HARD', '1980', '1985', '1992', '1971', 'B', 'SAARC was established at a Dhaka summit in December 1985.', null),
(200, 'general-knowledge', 'General Knowledge', 'Who moved the Lahore (Pakistan) Resolution in 1940?', 'MCQ', 'HARD', 'Allama Iqbal', 'Sir Syed Ahmad Khan', 'Chaudhry Rahmat Ali', 'A. K. Fazlul Haq', 'D', 'The resolution was moved by A. K. Fazlul Haq (Bengal) and seconded by Chaudhry Khaliquzzaman. End of mock test. Best of luck for PMA Long Course 159.', null)
),
question_upserts as (
  insert into public.questions (subject_id, question_text, question_type, difficulty, option_a, option_b, option_c, option_d, correct_option, explanation, image_url, source, is_verified, is_active, content_key, category, priority, source_type, source_reference)
  select subject.id, seed.question_text, seed.question_type, seed.difficulty, seed.option_a, seed.option_b, seed.option_c, seed.option_d, seed.correct_option, seed.explanation, seed.image_url,
         '1st full Mock Test project PDF', false, true, 'first-full-mock-test-q' || lpad(seed.question_number::text, 3, '0'), seed.category, 'MEDIUM', 'PREPARATION_PATTERN', 'Source: Full mock tests/1st full Mock Test.pdf'
  from first_full_mock_seed seed join public.subjects subject on subject.slug = seed.subject_slug
  on conflict (content_key) where content_key is not null do update set
    subject_id = excluded.subject_id, question_text = excluded.question_text, question_type = excluded.question_type, difficulty = excluded.difficulty,
    option_a = excluded.option_a, option_b = excluded.option_b, option_c = excluded.option_c, option_d = excluded.option_d, correct_option = excluded.correct_option,
    explanation = excluded.explanation, image_url = excluded.image_url, is_active = true, category = excluded.category, priority = excluded.priority, source_type = excluded.source_type, source_reference = excluded.source_reference, updated_at = now()
  returning id, content_key
)
select count(*) from question_upserts;

delete from public.mock_test_questions link using public.mock_tests test where link.mock_test_id = test.id and test.slug = 'first-full-mock-test';

insert into public.mock_test_questions (mock_test_id, question_id, question_number)
select test.id, question.id, numbered.question_number
from generate_series(1, 200) as numbered(question_number)
join public.questions question on question.content_key = 'first-full-mock-test-q' || lpad(numbered.question_number::text, 3, '0')
join public.mock_tests test on test.slug = 'first-full-mock-test'
order by numbered.question_number;

do $$
declare v_mock_id uuid;
begin
  select id into v_mock_id from public.mock_tests where slug = 'first-full-mock-test' and is_active and total_questions = 200;
  if v_mock_id is null or (select count(*) from public.mock_test_questions where mock_test_id = v_mock_id) <> 200 then
    raise exception 'The first full mock test must have exactly 200 linked questions';
  end if;
  if (select count(*) from public.mock_test_questions where mock_test_id = v_mock_id and question_number between 61 and 120 and question_id in (select id from public.questions where image_url is not null)) <> 58 then
    raise exception 'The non-verbal figure crops do not match the source paper';
  end if;
  if exists (select 1 from public.mock_test_questions link join public.questions question on question.id = link.question_id where link.mock_test_id = v_mock_id and (question.correct_option not in ('A', 'B', 'C', 'D') or question.option_a is null or question.option_b is null or question.option_c is null or question.option_d is null)) then
    raise exception 'Every full mock question must have four options and a correct answer';
  end if;
end $$;

commit;
